// FIX: The Deno types reference was failing to resolve. 
// Switched to a more stable esm.sh URL as seen in official examples to ensure Deno runtime types are loaded.
/// <reference types="https://esm.sh/@supabase/functions-js@2.4.1/src/edge-runtime.d.ts" />

// IMPORTANT: The Supabase Edge Runtime (Deno) requires full URL imports.
// We are using esm.sh, a CDN that provides ES modules for npm packages.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { GoogleGenAI } from "https://esm.sh/@google/genai@0.14.1"
import { corsHeaders } from '../_shared/cors.ts'

console.log("Dream Team Edge Function Initialized");

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { type, profile, prompt, context } = await req.json()

    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    )

    const authHeader = req.headers.get('Authorization')!
    const { data: { user } } = await supabaseAdmin.auth.getUser(authHeader.replace('Bearer ', ''));
    if (!user) {
      return new Response(JSON.stringify({ error: 'User not authenticated' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }
    
    const provider = type === 'summarize' ? 'gemini' : profile.provider;
    console.log(`Request received for user ${user.id} from provider ${provider}`);

    const { data: apiKeyData, error: apiKeyError } = await supabaseAdmin
      .from('api_keys')
      .select('encrypted_key')
      .eq('user_id', user.id)
      .eq('provider', provider)
      .single()

    if (apiKeyError || !apiKeyData) {
      console.log(`No API key found for ${provider}. Returning mock response.`);
      const mockResponse = `This is a mocked response from the secure server. The API key for '${provider}' is not configured in your account.`;
      return new Response(`data: ${JSON.stringify({ text: mockResponse })}\n\n`, { headers: { ...corsHeaders, 'Content-Type': 'text/event-stream' } });
    }

    const apiKey = apiKeyData.encrypted_key;

    if (type === 'generate') {
      if (profile.provider === 'gemini') {
        const ai = new GoogleGenAI({ apiKey });
        
        let fullPrompt = prompt;
        if (context && context.length > 0) {
          const history = context.map((msg: any) => `Output from agent "${msg.aiId}":\n${msg.content}`).join('\n\n');
          fullPrompt = `The main goal is: "${prompt}"\n\nHere is the discussion so far:\n\n${history}\n\nBased on all the information above, provide your contribution.`;
        }

        const contents = {
          role: 'user',
          parts: [{ text: fullPrompt }]
        };

        const resultStream = await ai.models.generateContentStream({
          model: profile.model,
          contents: [contents],
          config: {
            systemInstruction: profile.systemInstruction,
          }
        });

        const stream = new ReadableStream({
          async start(controller) {
            for await (const chunk of resultStream) {
              const chunkText = chunk.text;
              if (chunkText) {
                controller.enqueue(new TextEncoder().encode(`data: ${JSON.stringify({ text: chunkText })}\n\n`));
              }
            }
            controller.close();
          },
        });
        return new Response(stream, { headers: { ...corsHeaders, 'Content-Type': 'text/event-stream' } });

      } else {
        const mockResponse = `(Mocked Server Response) Agent: ${profile.name} (${profile.model})\nPrompt: "${prompt}"`;
        return new Response(`data: ${JSON.stringify({ text: mockResponse })}\n\n`, { headers: { ...corsHeaders, 'Content-Type': 'text/event-stream' } });
      }
    } 
    else if (type === 'summarize') {
      return new Response(JSON.stringify({
        title: "Mocked Summary from Server",
        overview: "This summary was generated by the secure backend.",
        points: [{ point: "The backend successfully processed the request.", sourceMessageIds: [] }]
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }
    
    throw new Error('Invalid request type specified');

  } catch (err) {
    console.error("Edge function error:", err);
    return new Response(JSON.stringify({ error: err.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    })
  }
})